version: "2"
services:
  elk:
    image: sebp/elk
    ports:
      - "5601:5601"
      - "9200:9200"
      - "5044:5044"
    volumes:
      - /dev/shm:/dev/shm
    environment:
      - es.bootstrap.seccomp=false
      - bootstrap.ignore_system_bootstrap_checks=true
    security_opt:
      - seccomp:unconfined 
